# Generated by Django 5.1.1 on 2024-09-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_service_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="banner",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
    ]
