# Generated by Django 5.1.1 on 2024-09-14 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_pricing"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pricing",
        ),
    ]
