# Generated by Django 5.1.1 on 2024-09-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_feature_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="image",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
