# Generated by Django 5.1.1 on 2024-09-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_portfolio_image_portfolio_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolio",
            name="number",
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="name",
            field=models.CharField(default="Product", max_length=100),
        ),
    ]
