# Generated by Django 5.1.1 on 2024-09-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0015_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="user_form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wed_date", models.DateField()),
                ("city", models.CharField(max_length=50)),
                (
                    "services",
                    models.CharField(
                        choices=[
                            (1, "Catering"),
                            (2, "Photography"),
                            (3, "Venue Booking"),
                        ],
                        max_length=50,
                    ),
                ),
                ("event_mgr", models.BooleanField()),
                ("budget", models.IntegerField()),
            ],
        ),
    ]
