# Generated by Django 5.1.1 on 2024-09-16 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_alter_user_form_budget_alter_user_form_city_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="user_form",
            new_name="UserForm",
        ),
    ]
