# Generated by Django 5.1.1 on 2024-09-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0020_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
