# Generated by Django 5.1.1 on 2024-09-16 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0022_userprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="phno",
            new_name="phone_number",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="utype",
            new_name="user_type",
        ),
    ]
