# Generated by Django 5.1.1 on 2024-09-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0023_rename_phno_userprofile_phone_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.CharField(max_length=500)),
            ],
        ),
    ]
