# Generated by Django 5.1.1 on 2024-09-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0025_alter_contact_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="name",
            new_name="provider_name",
        ),
        migrations.AddField(
            model_name="service",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="service_cost",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="service_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="service_type",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
