# Generated by Django 5.1.1 on 2024-09-18 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0026_rename_name_service_provider_name_service_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="service",
            name="service_type",
        ),
        migrations.RemoveField(
            model_name="service",
            name="start_date",
        ),
    ]
