# Generated by Django 5.1.1 on 2024-09-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0027_remove_service_end_date_remove_service_service_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="banner",
            field=models.ImageField(
                blank=True, default="fallback.png", upload_to="uploads/"
            ),
        ),
    ]
