# Generated by Django 5.1.1 on 2024-09-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0028_alter_service_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="banner",
            field=models.ImageField(
                blank=True, default="fallback.png", upload_to="uploads/"
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="image",
            field=models.ImageField(
                blank=True, default="fallback.png", upload_to="uploads/"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="reviewer_image",
            field=models.ImageField(
                blank=True, default="fallback.png", upload_to="uploads/"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="image",
            field=models.ImageField(
                blank=True, default="fallback.png", upload_to="uploads/"
            ),
        ),
    ]
