# Generated by Django 5.1.1 on 2024-12-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0030_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="total",
        ),
    ]
