# Generated by Django 5.1.4 on 2024-12-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_cart_quantity_remove_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_cost',
        ),
        migrations.AddField(
            model_name='service',
            name='advance_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='est_final_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
